`timescale 1ns / 1ps

// ============================================================================
// Module: neural_eq_top_new
// Description: New top-level wrapper that instantiates 7 sub-modules to
//              implement the same neural network equalizer as neural_eq_top.
//              All ports and behaviour are identical to neural_eq_top.
//
//  Sub-module hierarchy:
//    1. input_window  — 5-tap sliding window + flush logic
//    2. layer1_fsm    — L1 FSM controller + input mux (4-cycle)
//    3. layer1_mac    — L1 32-neuron MAC array  (ReLU output)
//    4. layer2_fsm    — L2 FSM controller + input mux (6-cycle)
//    5. layer2_mac    — L2 32-neuron MAC array  (ReLU output)
//    6. layer3_fsm    — L3 FSM controller + input mux (6-cycle)
//    7. layer3_mac    — L3 2-neuron output MAC  (saturate, no ReLU)
// ============================================================================
module neural_eq_top_new (
    input  logic clk, rst_n,
    input  logic valid_in,
    input  logic signed [15:0] in_I, in_Q,
    output logic signed [15:0] out_I, out_Q,
    output logic valid_out
);

    // -------------------------------------------------------------------------
    // Inter-module wires
    // -------------------------------------------------------------------------

    // input_window -> layer1_fsm
    logic [79:0] win_I_flat;
    logic [79:0] win_Q_flat;
    logic        v_win;

    // layer1_fsm -> layer1_mac
    logic signed [15:0] l1_in1, l1_in2, l1_in3;
    logic [2:0]         l1_tick;
    logic               l1_busy;
    logic               v_l1;

    // layer1_mac -> layer2_fsm
    logic [511:0] l1_out_flat;

    // layer2_fsm -> layer2_mac
    logic signed [15:0] l2a_in1, l2a_in2, l2a_in3;
    logic signed [15:0] l2b_in1, l2b_in2, l2b_in3;
    logic [2:0]         l2_tick;
    logic               l2_busy;
    logic               v_l2;

    // layer2_mac -> layer3_fsm
    logic [511:0] l2_out_flat;

    // layer3_fsm -> layer3_mac
    logic signed [15:0] l3a_in1, l3a_in2, l3a_in3;
    logic signed [15:0] l3b_in1, l3b_in2, l3b_in3;
    logic [2:0]         l3_tick;
    logic               l3_busy;
    logic               v_l3;  // generated by layer3_fsm (unused externally)

    // -------------------------------------------------------------------------
    // 1. Input Window
    // -------------------------------------------------------------------------
    input_window u_input_window (
        .clk      (clk),
        .rst_n    (rst_n),
        .valid_in (valid_in),
        .in_I     (in_I),
        .in_Q     (in_Q),
        .win_I_flat(win_I_flat),
        .win_Q_flat(win_Q_flat),
        .v_win    (v_win)
    );

    // -------------------------------------------------------------------------
    // 2. Layer 1 FSM + Input Mux
    // -------------------------------------------------------------------------
    layer1_fsm u_layer1_fsm (
        .clk    (clk),
        .rst_n  (rst_n),
        .win_I_flat(win_I_flat),
        .win_Q_flat(win_Q_flat),
        .v_win  (v_win),
        .l1_in1 (l1_in1),
        .l1_in2 (l1_in2),
        .l1_in3 (l1_in3),
        .l1_tick(l1_tick),
        .l1_busy(l1_busy),
        .v_l1   (v_l1)
    );

    // -------------------------------------------------------------------------
    // 3. Layer 1 MAC Array
    // -------------------------------------------------------------------------
    layer1_mac u_layer1_mac (
        .clk    (clk),
        .rst_n  (rst_n),
        .l1_in1 (l1_in1),
        .l1_in2 (l1_in2),
        .l1_in3 (l1_in3),
        .l1_tick(l1_tick),
        .l1_busy(l1_busy),
        .v_win  (v_win),
        .l1_out_flat(l1_out_flat)
    );

    // -------------------------------------------------------------------------
    // 4. Layer 2 FSM + Input Mux
    // -------------------------------------------------------------------------
    layer2_fsm u_layer2_fsm (
        .clk     (clk),
        .rst_n   (rst_n),
        .l1_out_flat(l1_out_flat),
        .v_l1    (v_l1),
        .l2a_in1 (l2a_in1),
        .l2a_in2 (l2a_in2),
        .l2a_in3 (l2a_in3),
        .l2b_in1 (l2b_in1),
        .l2b_in2 (l2b_in2),
        .l2b_in3 (l2b_in3),
        .l2_tick (l2_tick),
        .l2_busy (l2_busy),
        .v_l2    (v_l2)
    );

    // -------------------------------------------------------------------------
    // 5. Layer 2 MAC Array
    // -------------------------------------------------------------------------
    layer2_mac u_layer2_mac (
        .clk     (clk),
        .rst_n   (rst_n),
        .l2a_in1 (l2a_in1),
        .l2a_in2 (l2a_in2),
        .l2a_in3 (l2a_in3),
        .l2b_in1 (l2b_in1),
        .l2b_in2 (l2b_in2),
        .l2b_in3 (l2b_in3),
        .l2_tick (l2_tick),
        .l2_busy (l2_busy),
        .v_l1    (v_l1),
        .l2_out_flat(l2_out_flat)
    );

    // -------------------------------------------------------------------------
    // 6. Layer 3 FSM + Input Mux
    // -------------------------------------------------------------------------
    layer3_fsm u_layer3_fsm (
        .clk     (clk),
        .rst_n   (rst_n),
        .l2_out_flat(l2_out_flat),
        .v_l2    (v_l2),
        .l3a_in1 (l3a_in1),
        .l3a_in2 (l3a_in2),
        .l3a_in3 (l3a_in3),
        .l3b_in1 (l3b_in1),
        .l3b_in2 (l3b_in2),
        .l3b_in3 (l3b_in3),
        .l3_tick (l3_tick),
        .l3_busy (l3_busy),
        .v_l3    (v_l3)
    );

    // -------------------------------------------------------------------------
    // 7. Layer 3 MAC Array (output layer)
    // -------------------------------------------------------------------------
    layer3_mac u_layer3_mac (
        .clk      (clk),
        .rst_n    (rst_n),
        .l3a_in1  (l3a_in1),
        .l3a_in2  (l3a_in2),
        .l3a_in3  (l3a_in3),
        .l3b_in1  (l3b_in1),
        .l3b_in2  (l3b_in2),
        .l3b_in3  (l3b_in3),
        .l3_tick  (l3_tick),
        .l3_busy  (l3_busy),
        .v_l2     (v_l2),
        .v_l3     (v_l3),
        .out_I    (out_I),
        .out_Q    (out_Q),
        .valid_out(valid_out)
    );

endmodule
